project:
  type: website

metadata-files:
  - _sidebar.yml

format:
  html:
    theme: journal
    sidebar: true

website:
  title: "statsframe"
  description: "Customizable data and model summaries in Python."
  favicon: "favicon.ico"
  page-navigation: false
  search:
    location: sidebar
    type: textbox
    limit: 10
  navbar:
    pinned: true
    search: true
    # logo: logo.png
    left:
      - text: "Get started"
        file: get_started.py
      - text: "Reference"
        file: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/nkeleher/statsframe
        aria-label: statsframe

quartodoc:
  style: pkgdown
  dir: reference
  package: statsframe
  sidebar: _sidebar.yml
  parser: sphinx

  sections:
    - title: datasummary
      desc: Customizable data and model summaries in Python.
      contents:
        - datasummary.skim_frame
