name: Publish to Test PyPI
on:
  push:
    tags:
      - "*.*.*"

jobs:
  test_pypi_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --without=dev
      - name: Run tests
        run: poetry run pytest tests/
      - name: Set Test PyPI repository
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - name: Get Test PyPI token
        run: poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}
      - name: Publish package to Test PyPI
        run: poetry publish --build -r testpypi
