name: Publish to Test PyPI
on:
  push:
    tags:
      - "*.*.*"

jobs:
  tests:
    name: "Tests"
    runs-on: ${{ matrix.os }}
    if: ${{ !github.event.pull_request.head.repo.fork }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: ["ubuntu-latest"]
        pytest_opts: ["--workers 4 --tests-per-worker 1"]
        include:
          - os: "ubuntu-latest"
            python: "3.12"
          - os: "macos-latest"
            python: "3.12"
            pytest_opts: "--workers 4 --tests-per-worker 1 -k statsframe/tests"
          - os: "windows-latest"
            python: "3.12"
            pytest_opts: "-k statsframe/tests"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --without=dev
      - name: Run tests
        run: poetry run pytest tests/
  test_pypi_release:
    needs: ["tests"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --without=test,dev
      - name: Set Test PyPI repository
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - name: Get Test PyPI token
        run: poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}
      - name: Publish package to Test PyPI
        run: poetry publish --build -r testpypi
